src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[Vich\Uploadable]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column]
    private ?bool $is_disponible = null;

    #[ORM\Column(length: 255)]
    private ?float $prix = 0.0;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $Categorie = null;

    #[Vich\UploadableField(mapping: 'product_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;
    
    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    
        /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function isIsDisponible(): ?bool
    {
        return $this->is_disponible;
    }

    public function setIsDisponible(bool $is_disponible): static
    {
        $this->is_disponible = $is_disponible;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): static
    {
        $this->Categorie = $Categorie;

        return $this;
    }

}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitFormType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class ProduitController extends AbstractController
{
    #[Route('/produit', name: 'listProduit')]

    public function listProduit(EntityManagerInterface $entityManager): Response
    {
        $repo = $entityManager->getRepository(Produit::class);
        $lesProduits = $repo->findAll();

        return $this->render('produit/index.html.twig', ['lesProduits' => $lesProduits]);
    }

    #[Route('/admin/produit/ajouter', name: 'app_produit_ajouter')]
    public function ajouter(Request $request, EntityManagerInterface $entityManager): Response
    {
        if (!$this->isGranted('ROLE_ADMIN')) {
            throw new AccessDeniedException('Access denied. You need to have the ADMIN role.');
        }
        $produit = new Produit();
        $form = $this->createForm(ProduitFormType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();
            $this->addFlash('success', 'Product added successfully');
            return $this->redirectToRoute('app_produit');
        }

        return $this->render('admin/produit/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/voir/{id}', name: 'app_produit_show')]
    public function voir(Produit $produit): Response
    {

        if (!$produit) {
            throw $this->createNotFoundException('Aucun produit trouvé pour l\'ID ' . $produit->getId());
        }

        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }
    
    #[Route('/admin/produit/edit/{id}', name: 'app_produit_edit')]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        
        $form = $this->createForm(ProduitFormType::class, $produit);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', 'Procut edited successfully');
            return $this->redirectToRoute('listProduit');
        }   
    
        return $this->render('admin/produit/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    // #[Route('/{id}', name: 'app_produit_delete')]
    //     public function delete(Request $request,ProduitRepository $produitRepository, EntityManagerInterface $entityManager, $id): Response
    //     {
    //         $produit = $produitRepository->find($id);

    //         // if (!$produit) {
    //         //     throw $this->createNotFoundException('No Prouct found for id '.$id);
    //         // }
    //         $entityManager->remove($produit);
    //         $entityManager->flush();
    //         // $this->addFlash('success', 'Produit a été supprimer avec succès.');
    
    //         return $this->redirectToRoute('listProduit');
    //     }
    }

templates/produit/index.html.twig
{% extends "base.html.twig" %}


{% block body %}

            <!-- Page Header Start -->
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Produit</h2>
                    </div>
                    <div class="col-12">
                        <a href="{{ path('app_home') }}">Home</a>
                        <a href="">Produit</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page Header End -->

<section class="shop_section layout_padding mb-5">
    <section class="container">
        <div class="heading_container heading_center">
            <h2>Latest Products</h2>
        </div>
        <div class="row">
            {% for produit in lesProduits %}
            <div class="col-sm-6 col-md-4 col-lg-3">
                <div class="box">
                    <a href="{{ path('app_produit_show', {'id': produit.id}) }}">
                    <div class="img-box">
                        <img src="{{ vich_uploader_asset(produit, 'imageFile') }}" alt="Hero Image" width="200" height:"180">
                    </div></a>
                    <div class="detail-box" style="display:block">
                        <h5>{{ produit.libelle }}</h4>
                        <p><span>{{ produit.prix }} dinars</span></p>
                    </div>
                    {# <div class="new"><span>New</span></div> #}
                    
                </div>
            </div>
        {% endfor %}
        </div>
    </section>
</section>

{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product Details{% endblock %}

{% block body %}
<style>


/*****************globals*************/

img {
  max-width: 100%; }

.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }   

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  /* padding: 1.2em 1.5em; */
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: red;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #85ad00; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

/*# sourceMappingURL=style.css.map */


</style>


<div class="container">
            <a href="{{ path('listProduit') }}" class="btn btn-light">Retour</a>

		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						<div class="preview-pic tab-content">
                        <img src="{{ vich_uploader_asset(produit, 'imageFile') }}" alt="Hero Image" width="200" height:"180">
						  <div class="tab-pane" id="pic-5">
                          </div>
						</div>
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{ produit.libelle }}</h3>
						<div class="rating">
							<span style="color:red" class="review-no">{{ produit.marque }}</span>
						</div>
						<p class="product-description">Suspendisse quos? Tempus cras iure temporibus? Eu laudantium cubilia sem sem! Repudiandae et! Massa senectus enim minim sociosqu delectus posuere.</p>
						<h4 class="price">current price: <span>{{ produit.prix }} dinars</span></h4>
                        <strong>Disponibility:</strong> {% if produit.isDisponible %}<span style="color:red">disponible</span>{% else %}<span>Non disponible</span>{% endif %}<br>  
						<div class="action">
							<button class="btn btn-warning" type="button">add to cart</button>
							<button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
                        </div>
					</div>
				</div>
			</div>
		</div>
	</div>           
{% endblock %}